# Deloppgave 4: Studiedesign

## Introduksjon

I denne oppgaven har jeg valgt ut 5 studier for å se på studiedesign og statistiske analyser, vurdere styrker og svakheter rundt dette og gi en anbefaling på hvordan framtidige studier bør utformes på bakgrunn av dette. Felles for studiene som er valgt ut, er at de sammenligner effekten av å bolklegge utholdenhetstrening (BP; blokk-periodisering) sammenlignet med tradisjonell strukturering av utholdenhetstrening (TP; tradisjonell-periodisering). Studiene har sett på påvirkningen på ulike utholdenhetsparameter som Vo2-maks, laktatterskel gjennom laktatprofil, submaksimal og maksimal aerob effekt og også prestasjonstester av ulik karakter. I denne oppgaven fokuserer jeg på effekten av BP på Vo2-maks. Studiene er naturligvis ikke helt likt utformet, men felles er at det bolklegging av intensiv trening, dvs intensitetssone 4/5 på Olympiatoppens intensitetsskala for utholdenhetstrening \[@OLT_int2021; Mølmen et al., 2019). (Obs; studiene deler ofte opp i 3 intensitetssoner istedenfor 3, så % av makspuls bør benyttes for å sammenligne intensitet mellom studiene). Kontrollgruppene som har benyttet seg av tradisjonell trening har i de fleste studiene hatt 2 (til 3) ukentlige intervalløkter med intensiv trening.

Studiene jeg har valgt ut er;

1.  «Effects of 12 weeks of block periodization on performance and performance indices in well-trained cyclists» [@ronnestad_effects_2014]

2.  «Block periodization of high-intensity aerobic intervals provides superior training effects in trained cyclists» [@ronnestad_block_2014]

3.  «5-week block periodization increases aerobic power in elite cross-country skiers» (Rønnestad et al., 2016)

4.  «No Differences Between 12 Weeks of Block- vs. Traditional-Periodized Training in Performance Adaptations in Trained Cyclists» [@almquist_no_2022]

5.  «Improved VO2max and time trial performance with more high aerobic intensity interval training and reduced training volume: a case study on an elite national cyclist» [@storen_improved_2012]

    \*Studie 1 og 2 er basert på samme forskningsprosjekt av samme forskere og utvalg. Dog har studie 1 sett på effekten av BP over en 12-ukersperiode, mens studie 2 har sett på effekten etter 4 uker.

## Studiedesign

Det kan brukes flere former for studiedesign når man skal forske på effekten av BP på utholdenhetsprestasjon og parametere. Studiedesign kan deles inn i flere ulike kategorier, men innenfor idrett er intervensjons- og observasjonsstudier mye brukt (Thiese, 2014). Intervensjonsstudier benytter seg som navnet tilsier av en intervensjon og ser på effekten av denne, mens i en observasjonsstudie påvirker ikke forskerne deltakerne, men ser på eventuell sammenheng mellom faktorer og utfall (Thiese, 2014). Studiene er enten retrospektive, altså bruker data som allerede er innsamlet, og forskerne kan dermed ikke påvirke studien i denne fasen. Fordeler med denne formen kan være at den er kostnadsbesparende og i mange tilfeller kan man bruke data fra en stor populasjon, men samtidig kan det være unøyaktighet i datainnsamlingen og forskerne får ofte ikke påvirket datainnsamlingen som det ønsker \[@hulley_designing_2013; @thiese_observational_2014\]. Ved prospektivt studiedesign følges deltakerne derimot framover i tid, og forskerne kan dermed designe forsøkene så de blir best mulige.\

Innenfor idrettsforskning blir studier ofte designet som en randomisert-kontrollert studie (randomized controlled trial; RCT) for å sammenligne effekten til det som forskes på opp mot en kontrollgruppe før og etter en intervensjon (Thiese, 2014). Ved at deltakerne er randomisert sikrer forskerne mot bias, altså at deres eventuelle forutinntatthet påvirker studien. I tillegg kan forsøkene standardiseres for å sikre reproduserbarhet (Hulley et al., 2013). Av studier plukket ut til denne oppgaven er samtlige intervensjons- og prospektive studier. Dog er studie 1 til 4 RCT-er, mens studie 5 er en casestudie. Alle studier er pre-post studier, altså ser de på effekten etter intervensjon sammenlignet før (Thiese, 2014). De 4 første studiene har et to-gruppe design, med en BP-gruppe og en TP-gruppe (kontroll). Kontrollgruppen har gjennomført det som karakteriseres som tradisjonell utholdenhetstrening, ofte referert som «best practice» i meta-analyser (Mølmen et al., 2019; Thiese, 2014), men med ulik utforming i studiene. Studiene kan derfor også kategoriseres som en form for aktivt kontrollerte studier da også kontrollgruppen har gjennomført en intervensjon (Hulley et al., 2013). Studiene gjennomførte hardøktene som høyintensiv intervalltrening, intensitetssone 4/5 [@OLT_int2021] \> 88% av HR-maks. Studie 4 hadde i tillegg intervalløkter på moderat intensitet (OLT-sone 3) kalt MIT for å se om dette ga effekt på submaksimale prestasjonsparametere (Almquist et al., 2022). \[-\@ Rønnestad et al., 20121 og 2 gjennomførte en 4-ukers syklus der uke 1 inneholdt 5 HIT-økter, mens uke 2-4 inneholdt 1 HIT-økt. Almquist et al. (2022) hadde også en syklus på 4-uker over en 12-ukers periode, men med mindre volum anliggende både lav, moderat og høy intensitet. Uke 1 inneholdt 4 moderat-intensitet økter (MIT) av 4*12minutter, 3 lav-intensitets økter (LIT) i uke 2 og 4 HIT økter av 5*5minutter i uke 3. Uke 4 var designert til restitusjon. Rønnestad et al., 2015 hadde en intervensjon bestående av 5 HIT-økter første uken, 3 i uke 3, mens resterende uker hadde 1 HIT-økt for BP-gruppen. Øktene ble gjennomført på 88-100% av HR-maks (Rønnestad et al., 2015) ved 5x6min og 6x5min økter. Støren et al. (2012) skiller seg et fra de andre studiene ikke bare gjennom å være en case-studie, men også gjennom intervensjonen som varte 1 år. Forsøkspersonen gjennomgikk 2 blokkperioder på 9 og 10 dager med henholdsvis 14 og 15 HIT-økter. Øktene besto av 4x4minutter på 90-95% av HR-maks. Studien hadde et within-subject design ettersom forsøkspersonen både gjennomførte BP- og TP-trening. Fordelen med dette er at man kan se effektene på samme forsøksperson, uten at individuelle forskjeller i treningsrespons påvirker. Dette med forutsetning at eventuell treningseffekt fra en periode påvirker den neste (Hulley et al., 2013) For framtidige studer synes randomiserte kontrollerte studier å gi gode data på effekten av BP vs. TP for effekt på Vo2-maks. Støren et al. Legger heller ikke skjul på at RCT var å foretrekke, men man kan likevel trekke fram noen styrker ved å bruke en case-studie. Blant annet var BP-periodene i studie 5 vesentlig mer intensiv, og forsøkspersonen viste periodevis tegn til overtreningssyndrom (Støren et al., 2012). Balansegangen mellom hva utøver kan akkumulere av trening før eventuelle symptomer på overtreningssyndrom oppstår er en hårfin balansegang, og her spiller også «high-risk high-reward» prinsippet inn. Jo tøffere intervensjon en utøver klarer å akkumulere, jo større effekt kan potensielt oppnås. Men dette er vanskeligere å få til med et utvalg på flere utøvere, da individuelle forskjeller og også etiske dilemmaer spiller inn. Man kan også i framtidige studier se på muligheter for bruk av crossover design, som også har blitt gjennomført tidligere av studier som ikke er tatt med i denne oppgaven (Garcia-Pallarés et al., 2010; McGawley et al., 2017; Manchado et al., 2018). Fordelene med dette kan være å se respons av BP og TP i samme individ, slik som i Støren et al., men her får man sett på flere individer samtidig. En utfordring med dette kan dog være om forsøkspersonene tar med seg eventuelle effekter fra f. eks BP inn i TP, slik at man ikke får sett effektene forårsaket kun av intervensjonen man nettopp har vært gjennom (Hulley et al., 2013). Et annet moment som kan være interessant å se på i fremtidige studier er en kontrollgruppe med mer utforskende design. I studiene som er med i denne oppgaven har samtlige hatt tilnærmet samme volum av trening på lav intensitet, utenom Støren et al. Selv om dette naturligvis forsvares med at det er effekten av selve bolkleggingen man vil se på, bør man likevel spørre seg om det gir svar på om bolklegging er det beste designet på treningsplaner for utholdenhetsutøvere. Tidligere studier har blitt kritisert for å ha et for ensidig treningsprogram i kontrollgruppa (Kiely, 2012), noe Rønnestad et. al tok til betraktning i sin studie i 2015 (studie 3). Her hadde kontrollgruppa 3 HIT-økter den ene uka under intervensjonen for å variere fra de 2 ukentlige HIT-øktene de resterende ukene. Jeg mener dette er et steg i en interessant retning, og her vil jeg også strekke det enda lenger i framtidige studier. Ettersom BP i studiene har hatt et stimulus fra blokkperiodiseringen, burde de også strengt tatt få større adaptasjoner enn TP ettersom volumet på lav intensitet er det samme. Det vil alltid være et dilemma i utholdenhetstrening hva man skal vektlegge i treningsarbeidet, og en hardbolk vil gjøre at treningsvolumet utenom må justeres deretter. Derfor vil det i praksis si at TP kan ha et større treningsvolum, som ville gitt et større stimuli.

## Statistiske analyser

Valget av statistiske analyser ser man gjenspeiles av studiedesignet i de respektive studiene. Ettersom studie 1-4 var RCT-studier med 2 grupper, brukes verktøy for å se korrelasjon mellom gruppene for å lete etter statistisk signifikans. Studiene (Rønnestad, Ellefsen, et al., 2014; Rønnestad, Hansen, et al., 2014; Rønnestad et al., 2016) regnet ut effektstørrelsen (ES) mellom gruppene som Cohen's d for å finne statistisk signifikans. Kriteriene satt som grenser for å tolke av ES var følgende; 0.0--0.2 triviell, 0.2--0.6 liten, 0.6--1.2 moderat, 1.2--2.0 stor, og \>2.0 veldig stor (Hopkins et al., 2009). Almquist et al. (2022) brukte derimot en mikset linjer modell med grupper definert som «fixed effects» og rettet ved bruk av Pre-verdier som et kovariat med SPSS v. 25 software. ANOVA ble brukt i studiene til Rønnestad et al., men i noe ulik grad. I studie 1 og 3 ble en to-veis repeterende analyse av varians for å evaluere differanser innad og mellom gruppene fra Pre til Post. I studie 1 og 2 ble uparrede students t-test brukt for å sammenligne gruppene ved baseline og gruppenes treningsvolum. Valg av statistiske tester påvirker resultatene i stor grad, og valget av tester bør overveies godt av forskerne. Med t-test kan man sammenligne om to grupper har forskjeller med statistisk signifikans seg imellom, mens med ANOVA kan man sammenligne 3 eller flere grupper for å se etter signifikans. Testene blir gjort opp mot hypotese (null-hypotese). Den åpenbare fordelen med t-test er mindre grad av risiko for error ettersom det kun er 2 grupper, mens med ANOVA blir risikoen for dette større. Samtidig er ANOVA bedre egnet for flere grupper, da den reduserer risikoen for error som vil forekomme ved en t-test på flere enn 2 grupper. Samtlige studier utenom case-studien til Støren et al. hadde en alpha-level på P \< 0,05.
