# Deloppgave 2: Laborasjonsrapport

## Introduksjon

Analyser av genuttrykk gjennom kvantitativ PCR i skjelettmuskulatur er rutine i treningsstudier (Kuang et al., 2018). Hvordan forsøkene gjennomføres og tolkes har stor betydning for reliabiliteten og reproduserbarheten til dataene, og det synes å være stor variasjon i protokoller og dataanalyser mellom ulike laboratorium og forskningsmiljøer. qPCR-målinger i idrettsvitenskapelig forskning er interresant å undersøke ettersom man kan se trenings-induserte endringer i genuttrykk i skjelettmuskulatur.

Prinsippet bak qPCR-testing er å følge prosessen til DNA polymerase-drevet amplifikasjon av DNA (PCR) i sanntid. Under PCR benyttes et termostabilt DNA-polymerase enzym til å syntetisere nye DNA-tråder komplimentært til DNA-seksvensene man ønkser å undersøke. Enzymet blandes med DNA-templatet, primere og nukleotider (Kuang et al., 2018). Deretter følger 3 syklisk repeterte prosesser; deling av trådene (denaturering), primerbinding (annealing) og syntese av nye DNA-tråder (extending). Avslutningsvis vil sekvensen man har satt seg ut bli amplifisert til milliarder av kopier, også kalt PCR-amplikoner. Alternative metoder til qPCR-testing er nortern blotting, in situ hybridization og tradisjonell PCR. Sammenlignet med tradisjonell PCR, er qPCR i stand til å oppdage amplifikasjonen av PCR-amplikonet (sluttproduktet) på slutten av hver amplifikasjonssyklus (Kuang et al., 2018). Dette gjennom å bruke et "fluorescent dye system" og et "thermocycler with fluorescence-detection capability". Sammenlignet med nortern blotting og in situ hybridization er qPCR enkelt og raskt å gjennomføre, og samtidig mer sensitiv og spesifikk.

## Metode

qPCR analyse ble gjennomført i molekylærlaben sammen med foreleser. Foreleser hadde på forhånd forberedt fortynnet cDNA prøver som vi skulle bruke til analyse. qPCR-reaksjoner ble gjennomført med fortynnet cDNA og en blandet masterblanding. Masterblandingen bestod av med SYBR-green 2X mastermix (5 μl), like deler primermix forward og reverse (1 μl) og 2 μl kjernefritt vann (H20). 2 μl med cDNA ble tilført mastermixen. Innholdet ble sentrifugert i 1 min på 1200rpm for å blande innholdet. Prøvene ble analysert i en sanntids PCR-system og med QuantStudio programvare (Applied Biosystems, Waltham, MA USA). PCR-systemet og QuantStudio analyserer antall sykluser som må til for at det fluoreserende signalet når cyclisk terskel. Semi-kvantitative målinger ble gjort med 47s rRNA F1R1 som referansegen (Wackerhage, 2014).

## Resultater

@tbl-res viser den sykliske terskelen for hvert målgen per prøve. Hvert tall viser antall sykluser før den sykliske terskelen ble oppnådd. Et lavere tall indikerer et større genuttrykk. Til tross for at vi ikke testet for MyCH2X genutrykk fikk vi en observasjon for MyCH2X på en prøve. Det er vanskelig å forklare hva årsaken til feil-observasjonen er, men vi mistenker at det skyldes feil-merkning under qPCR-syklusene.

```{r}
#| echo: false
#| warning: false
#| error: false
#| label: "tbl-res"
#| tbl-cap: "qPCR Results"
library(readxl)
library(tidyverse)
library(gt)
qpcr_data <- read_excel("qpcr_data.xlsx", 
    sheet = "Results", range = "A20:J52") %>% 
  select(sample = `Sample Name`,  gene = `Target Name`, value = CT) %>% 
  pivot_wider(names_from = gene,
              values_from = value)
qpcr_data %>% 
  gt() %>% 
  fmt_number(columns = `MHC1 F1R1`:`47s rRNA F1R1`, decimals = 2) %>% 
  cols_label(sample = "Sample Number")
```
